import fs from 'node:fs';
import path from 'node:path';
import { ROOT, REFERENCE_LANGUAGE, listLanguageDirs, listNamespaces } from './lib.ts';

const ident = (s: string) => s.replace(/[^a-zA-Z0-9_$]/g, '_');

const languages = listLanguageDirs();
const referenceNamespaces = listNamespaces(REFERENCE_LANGUAGE);
const imports: string[] = [];
const bodies = new Map<string, string>();

for (const lang of languages) {
    const nsEntries: string[] = [];
    for (const ns of listNamespaces(lang)) {
        const name = `${ident(lang)}_${ident(ns)}`;
        imports.push(`import ${name} from '../locales/${lang}/${ns}.json';`);
        nsEntries.push(`    ${JSON.stringify(ns)}: ${name},`);
    }
    bodies.set(lang, `{\n${nsEntries.join('\n')}\n}`);
}

const indent = (s: string) => s.replace(/\n/g, '\n    ');
const others = languages.filter((l) => l !== REFERENCE_LANGUAGE);

const source = `// Generated by scripts/generate-resources.ts. Do not edit.
${imports.join('\n')}

const reference = ${bodies.get(REFERENCE_LANGUAGE)};

export type DefaultResources = typeof reference;
export type Namespace = keyof DefaultResources;
export interface TranslationTree {
    [key: string]: string | TranslationTree;
}
export type Language = ${languages.map((l) => JSON.stringify(l)).join(' | ')};
export type Resources = { ${REFERENCE_LANGUAGE}: DefaultResources } & {
    [L in Exclude<Language, '${REFERENCE_LANGUAGE}'>]: Partial<Record<Namespace, TranslationTree>>;
};

export const languages: readonly Language[] = ${JSON.stringify(languages)};
export const namespaces: readonly Namespace[] = ${JSON.stringify(referenceNamespaces)};

export const resources: Resources = {
    ${REFERENCE_LANGUAGE}: reference,
${others.map((l) => `    ${JSON.stringify(l)}: ${indent(bodies.get(l)!)},`).join('\n')}
};
`;

const out = path.join(ROOT, 'src', 'resources.ts');
fs.writeFileSync(out, source);
console.log(
    `Wrote ${path.relative(ROOT, out)} (${languages.length} languages, ${referenceNamespaces.length} namespaces)`
);
